/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#e1f4f7',
        'surface-tint': '#106685',
        'on-primary-fixed': '#001e2b',
        'tertiary-fixed-dim': '#89d6b3',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-container': '#1f7053',
        'on-primary': '#ffffff',
        'on-background': '#0d1e20',
        outline: '#70787e',
        'inverse-surface': '#223335',
        'on-tertiary-container': '#a3f0cc',
        'on-surface': '#0d1e20',
        'surface-container-highest': '#d3e6e8',
        tertiary: '#00573d',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#261900',
        surface: '#ffffff',
        'surface-container-low': '#FDFAF4',
        error: '#ba1a1a',
        secondary: '#735b28',
        'on-tertiary-fixed': '#002115',
        'outline-variant': '#bfc8ce',
        'primary-container': '#1a6b8a',
        'on-tertiary-fixed-variant': '#005139',
        'on-secondary-container': '#785f2b',
        'surface-dim': '#cbdee0',
        'secondary-container': '#fedb9c',
        'secondary-fixed': '#ffdea3',
        'on-surface-variant': '#40484d',
        background: '#F5F0E8',
        'tertiary-fixed': '#a5f3ce',
        'surface-variant': '#d3e6e8',
        'surface-bright': '#eafdff',
        'primary-fixed-dim': '#8bcff2',
        'on-tertiary': '#ffffff',
        'surface-container': '#def1f4',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#d9ecee',
        'secondary-fixed-dim': '#e3c285',
        'on-primary-container': '#bce7ff',
        'on-secondary-fixed-variant': '#594312',
        'primary-fixed': '#c0e8ff',
        'inverse-primary': '#8bcff2',
        'on-primary-fixed-variant': '#004d66',
        primary: '#00526d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '32px',
        'container-max-width': '1440px',
        'sidebar-width': '256px',
        gutter: '24px',
        'base-unit': '8px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-semibold': ['16px', { lineHeight: '1.5', fontWeight: '600' }],
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-medium': ['16px', { lineHeight: '1.5', fontWeight: '500' }],
        'label-sm': ['13px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-base': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        caption: ['13px', { lineHeight: '1.4', fontWeight: '400' }],
        h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
      },
      boxShadow: {
        warm: '0 2px 12px rgba(28, 45, 47, 0.08)',
      },
    },
  },
  plugins: [],
};
