"""password_changed_at

Revision ID: 11ba21d8f1cc
Revises: c3d8e2f0a1b9
Create Date: 2026-07-02 12:44:15.087388

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '11ba21d8f1cc'
down_revision: Union[str, None] = 'c3d8e2f0a1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'password_changed_at')
    # ### end Alembic commands ###
