"""initial

Revision ID: af198b38d651
Revises: 
Create Date: 2026-06-01 17:58:35.881814

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'af198b38d651'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('capacidad_maxima', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departamentos_id'), 'departamentos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'OPERADOR', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('INGRESO', 'EGRESO', name='tipomovimiento'), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('id_departamento', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_id'), 'movimientos', ['id'], unique=False)
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=255), nullable=False),
    sa.Column('id_departamento', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_egreso', sa.Date(), nullable=False),
    sa.Column('monto_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_pesos', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PARCIAL', 'PAGADO', 'CANCELADO', name='estadoreserva'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservas_id'), 'reservas', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('monto_original', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('ARS', 'USD', name='moneda'), nullable=False),
    sa.Column('medio_pago', sa.String(length=50), nullable=False),
    sa.Column('descuento_tipo', sa.Enum('PORCENTAJE', 'MONTO', name='descuentotipo'), nullable=True),
    sa.Column('descuento_valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_final', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_reserva'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_reservas_id'), table_name='reservas')
    op.drop_table('reservas')
    op.drop_index(op.f('ix_movimientos_id'), table_name='movimientos')
    op.drop_table('movimientos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_departamentos_id'), table_name='departamentos')
    op.drop_table('departamentos')
    # ### end Alembic commands ###
