"""usuarios

Revision ID: ecd1c25abeb3
Revises: af198b38d651
Create Date: 2026-06-09 20:36:24.099878

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ecd1c25abeb3'
down_revision: Union[str, None] = 'af198b38d651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.create_index(op.f('ix_usuarios_nombre'), 'usuarios', ['nombre'], unique=True)
    op.drop_column('usuarios', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_usuarios_nombre'), table_name='usuarios')
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###
